### ISSUE TITLE
Is there a way to bootstrap the connection process with a desired goTenna address?

### ISSUE THREAD

**Issue by radarku** [gotenna/PublicSDK#11]
If I have a bunch of goTenna in pairing mode, the one that I actually pair to when I run `GTConnectionManager.getInstance().scanAndConnect();` seems to be non-deterministic, even if I don't execute `GTConnectionManager.getInstance().clearConnectedGotennaAddress();`

Is there some way for me to bootstrap the connection process with the address of the goTenna that I want to connect to?

**Comment by tcolligan-ap** [comment]
@radarku The first time you try to use the SDK to scan for a goTenna, it will simply connect to whichever one it discovers first, which typically will be the goTenna that is closest to your mobile device.

Because this is how it work, we have a lot of specific instructions in our own mobile app that tells users to make sure that all other goTenna devices are turned off before they start the pairing process.

After the SDK has successfully connected to that first goTenna, the SDK saves that goTenna's Bluetooth MAC address. This way, when you call `scanAndConnect` in the future, it will know to only connect to that specific goTenna.

The purpose of `clearConnectedGoTennaAddress` is to clear out that saved goTenna address so that you can use the SDK to connect to any goTenna you want again.

There is currently no SDK functionality that would allow you to bootstrap the connection process to the address of a specific goTenna initially from outside the SDK. This is something that we could potentially add on Android. However for iOS we cannot access the actual Bluetooth MAC address of the goTenna, and instead are give an address that is generated by Apple and need to use that instead.

So for the iOS SDK this kind of functionality is probably not possible but on Android it may be.

I am assuming you would want a function call where in `scanAndConnect` you could pass in the Bluetooth MAC address of the goTenna you know you want to connect to so that it only connects to that specific one?

**Comment by radarku** [comment]
Understood regarding first time connecting, but on subsequent pairings, I'm
not seeing the behavior you describe where scanAndConnect will reconnect to
the previously paired device.  I'm not calling
clearConnectedGoTennaAddress(), and it often will pair with a different
goTenna each time I start-up.

How are you persisting the MAC address across app restarts?

**Comment by tcolligan-ap** [comment]
The value is persisted by saving it to shared preferences using the context passed in via `GoTenna.setApplicationToken`, perhaps that is the root of the issue? 

You should be able to call `GTConnectionManager.getInstance().getConnectedGotennaAddress()` to see if it remembers the MAC address or not.
