### ISSUE TITLE
Connecting and Disconnecting

### ISSUE THREAD

**Issue by dferg7** [gotenna/PublicSDK#15]
So, I'm in a bit of a rough spot and I'm hoping someone can shed some light on the situation or offer some ideas as to what I should do. 

Currently, I've written an application with the goTenna sdk (similar to the goTenna sample app) so that users can do the following: scan for a goTenna, echo success, get system info, set GID, broadcast, stop broadcast, and disconnect. I'm having issues with is the connect/disconnect process. Here's what I'm aiming for: if it is the first time the goTenna is being scanned then an alert dialog will pop up prompting for them to pick a GID, otherwise if they were already connected but chose to disconnect their goTenna (or they got disconnected), when they scan for a goTenna again (this will not be the first scan), an alert dialog will show prompting the user to either choose the same GID that was previously saved on the goTenna or select a new GID. The same GID option would do nothing and close the alert dialog while the new GID option would prompt the GID user alert dialog allowing them to pick a different GID and the Username/GID get updated. 

I have written the code to do all of this, however I've come across two issues. 
1) When the application is closed and onDestroy() is called, I call GTConnectionManager.getInstance().clearConnectedGotennaAddress() to clear the connected goTenna address on the phone and I also call UserDataStore.getInstance().deleteCurrentUser() to delete the current user that is stored on the goTenna. When the application is restarted and the user scans for a goTenna, the old goTenna address is still saved in the goTenna. What would be the proper way to clear the stored goTenna information when the application is closed? I didn't see one, but is there a 'forget user' method? 

2) Similar to the sample app, I use the onConnectionStateUpdated(GTConnectionManager.GTConnectionState gtConnectionState) method with the switch(gtConnectionState) and the case CONNECTED. For the case CONNECTED there is a simple if else statement that will display the alert dialogs according to whether or not this is the first time scanning for a goTenna. The issue with this is that if the user decides to disconnect and then scan for a goTenna again, the alert dialog pops up twice. If the user decides to disconnect and scan again then the alert dialog pops up three times, and then four times, and so on. The reason I believe this is happening is because the enum CONNECTED is placed into a for loop in the GTConnectionManager class and each time the CONNECTED case happens the for loop is updated to include that connection. Is there a reason as to why it continually places the CONNECTED case into the for loop? Is there a way to clear the CONNECTED state each time you scan for a goTenna? I know if you close the application and open and scan for a goTenna the CONNECTED state is now set back at 0.

**Comment by tcolligan-ap** [comment]
@dferg7 For issue #1 it is not exactly clear to me why you think you need to call those two methods for the situation you described? Calling `clearConnectedGotennaAddress()` should simply allow you to pair with any potential goTenna after you call it, including the one you were just paired with. If you do not call this function, then the user will only be able to pair with the goTenna they last paired with.

Calling `deleteCurrentUser() ` will only delete the user inside the local cache used in the SDK, it will not do anything on the actual goTenna. When you set a GID on a goTenna, it keeps that GID until it is overwritten by another GID. When your user wants to change GIDs, I would suggest calling `GTCommandCenter.getInstance().setGoTennaGID()` since that will take care of setting the GID on the goTenna and creating a local user object. Can you try to clarify what you are trying to accomplish by calling both these functions?

For issue #2 It sounds like you are calling `addGtConnectionListener(` multiple times on the same object without calling `removeGtConnectionListener(` which would explain why you are getting multiple notifications about the connection state. The for loop in that function is simply to be able to notify multiple listeners who wish to listen for that event.

Hopefully that clarified a few things for you.

**Comment by dferg7** [comment]
Okay, so clearConnectedGotennaAddress() actually clears the Bluetooth mac address that was recorded and not the GID? Sorry I believe I misunderstood the two methods (I'm still learning Java). I was ultimately trying to clear the GID on the goTenna if the user disconnected the goTenna, but now I see that the goTenna will keep that GID until overwritten. 

I will attempt to make the changes you suggested and thank you for the clarification.
