### ISSUE TITLE
Group creation processus

### ISSUE THREAD

**Issue by ZeDvD** [gotenna/PublicSDK#17]
Hi

Can you detail how to create group, what is the process, and what is the behaviour of the SDK and the goTenna.

What I want to do is to create a group, for instance with 4 members, 
May be all the members are not present at the moment I create the group, they will join later. Is it possible once the group is created

I do the following:  
- I know all the user GIDs before creating the group (they are statically defined)
- I call createGroupWithGIDs : for instance with 4 GID in my list. my problem : This methods needs at least 30 seconds to return. Why ? Is it because all my goTenna are not connected ? Is it waiting for all the group members ?
- Do I need to call createGroupWithGIDs  ? If I statically define a group ID that all my members know, can I use it ?
- Is there only one person that create the group, and the other join the group ? How do they join the group in this case ? What is the group creation / join process exactly ?
- Last question : can we have a group with 2 person only ? (current user and another one)

**Comment by tcolligan-ap** [comment]
@ZeDvD Yes `createGroupWithGIDs` is the correct method to use. What happens when you call that method is the following.

- For every group member you supplied to that function, the SDK will attempt to send a private message to that group member. The private message will contain an invitation to that group.
- The method is taking 30 seconds to return because it is attempting to contact every member in the group first. In addition, if you have never talked to a group member before, the sdk is going to have to do a key exchange with that member, adding more time.
- Only one person creates the group, and the other automatically join when they receive the invite.
- You can detect when you receive an invitation in the generic listener callback for messages `GTMessageListener` and `void onIncomingMessage(GTBaseMessageData baseMessageData)`and you do `if (baseMessageData instanceof GTGroupCreationMessageData)` then you can detect that you just received an invitation. By the time you detect the invite the SDK has already taken care of adding you to the group.
- You can remove yourself from a group by calling `GTCommandCenter.getInstance().deleteGID(` on the group's GID.
- It is possible to create a group with only 2 people, but that would essentially be a private conversation, so in our own app, we do not allow users to create a group with less than 3 people.

Hope that was helpful, if you have any other questions let me know.

**Comment by ZeDvD** [comment]
Great ! Thank you for all your answers ...

**Comment by ZeDvD** [comment]
Other questions :
- I succeeded to create groups, but only if the in the GID I have at least 9 numbers. If I have only 3 numbers, or 7 for instance, the group creation does not work. Why ?
- I don't use UserDataStore : I have my own user datamotel. Is it mandatory tu use the UserDataStore provided with the SDK to mémorise the users ? Why ?

**Comment by tcolligan-ap** [comment]
@ZeDvD Do you mean that when you supply `createGroupWithGIDs` with a list of GIDs, if any of the GIDs in that list are less then 9 digits long the group creation will fail?

Also, you dont have to use `UserDataStore` but it is automatically updated whenever you call `setGTGID`. As soon as you use the SDK to connect to a goTenna, it will set the GID on the goTenna to be whatever is set in the `UserDataStore` so I am not sure why you wouldn't want to use it?

**Comment by ZeDvD** [comment]
Yes, that's it. I request a group creation with four GIDs. I only have two antennas whose IDs are 1234 and 1231 (I will receive two other gotennas as soon as the mesh will be available). I don't receive the "incomingMessage" notification. If I put the two following IDs : 123456781 and 123456784, I receive the invite notification.

I don't use UserDataStore because my App can communicate with Gotenna or with a 3G web server. So I need an independant user manager from Gotenna when communicating in 3G : I have my own user List - simple to do...

**Comment by tcolligan-ap** [comment]
@ZeDvD Ok, I will log that as a bug in our internal tracker and we will take a look into it to see what the issue is when we have a chance. We only ever tested with larger GIDs since our own app only uses 10 - 14 digit GIDs, so thanks for bringing that to our attention.

**Comment by ZeDvD** [comment]
Another question about group dialog : in my App, I send group invitation from antenna 1. Antenna 2 receives the invite and so I get the group ID. From the antenna 2, is there something to do before sending messages ? Because I try to send messages to the group ID I received, and it does not work : I don't get any notification in the incomingMessage method, neither on smartphone 1, nor on smartphone 2 (I tried to send messages from both smartphone)

I tried someting else : I use my App and your sample app. I connected them together with a group, I receive the Invite Message in my App (sent from your app). So I get the group ID which is the same thant the one in your app. If I send a message to your App, using this group ID, your app receives it. But if I try to send back from your app to my App, I don't receive the msg sent.

So I think that I forgot something after receiving the group invite message from your app, in order to get your messages, but I don't understand what. Is there a call to perform ? I called the "startListening()" to initialise the message listener. Any idea ?

**Comment by tcolligan-ap** [comment]
@ZeDvD There should not be anything additional that you need to do to get groups to work. After you use your app to create a group, and you try to send a message to that group, do you see both Antennas flash to indicate that they received the group message?

This is the flow you should see
- You use goTenna 1 to create 'group A' and invite goTenna 2 into the group
- goTenna 2 receives the invite to 'group A'
- You send a message like "Hi" to 'group A'
- goTenna 2 should flash after you send "hi" to indicate it received the message

If goTenna 2 is flashing that means everything should be setup properly, since goTenna 2 now knows to listen for messages addressed to group 2.

If it does not flash when you send "Hi" it means goTenna 2 does no know about the group and something did not happen correctly inside the sdk.

Can you tell me what you see in this situation?

**Comment by ZeDvD** [comment]
myApp = goTenna1
Your test app = GoTenna 2
MyApp creates the group. Your app receives it.
In your app, activity "send group message", I select the group ID.
My App send "HI". Both gotenna flash. Your app receives "HI" : OK !
Your App sends "HI". Only gotenna 2 flash, gotenna 1 doesn't flash : My app does not receive the message. Any idea ?

**Comment by ZeDvD** [comment]
Ok, I just made a simple app, with group creation and message sent, and it runs correctly. So I suppose I have a bug in my own biggest app.
Nevertheless, I confirm that GID avec 3 digits doesn't run correctly : groups are not created.
I continue to debug and comeback if necessary. Thank you for your help!
