### ISSUE TITLE
IntentService for Android background process?

### ISSUE THREAD

**Issue by fiskurgit** [gotenna/PublicSDK#27]
It's unclear from the sample app but it looks like the example will only operate while both/all users have the app in the foreground. In my own quickly made app messages sent while the other device is not running the app don't get delivered.

Couple of questions:

1 - Have I misunderstood the SDK or would building a real-world app require messages to be received by a GoTenna api instance running in an IntentService? or is the problem detailed above an implementation error by myself?

2 - or is there some mechanism in the GoTenna unit itself that stores messages received that can then be retrieved by the app when running at a later time? (If not, this would be nice!)

Thanks,
Fisk

**Comment by tcolligan-ap** [comment]
Hi Fisk,

1. When the sample app is launched, it creates a Bluetooth connection to the goTenna which can operate in the background i.e.) If you background the app instead of killing it, the Bluetooth connection should remain, and you should be able to receive messages via the typical callbacks. The app in this state will eventually be killed by the Android OS if it stays in the background for too long, which is fairly standard. The Bluetooth API instance does not currently run in a background IntentService since we only wanted the Bluetooth connection to remain alive while the app itself was alive.

2. The goTenna unit itself does have it's own cache to store messages it received while it is not connected to an app. When an app connects to the unit later, it will pull all the stored messages as soon as it connects. Obviously both goTenna units need to actually be on for this to happen.

I hope that answers your questions.

**Comment by fiskurgit** [comment]
Okay - that actually raises far more questions than it answers, why has a messaging api been engineered without a daemon process; you can only receive messages for the lifecycle of your ephemeral Activity, as you say the OS can destroy this at any point once the app is in the background, on older low-memory devices or devices where the user is switching between a lot of high memory apps this could be seconds and should not have been used as a mechanism for allowing background processing.

"we only wanted the Bluetooth connection to remain alive while the app itself was alive" - why? That massively limits the usefulness of GoTenna for it's intended purpose. In order for two remote parties to exchange messages they'd both have to be running the app at the same time - how would party A know party B was trying to instigate communication?

Is this true of the official app too?

**Comment by fiskurgit** [comment]
I'm attempting to wrap the SDK in a job service so at least users can still be alerted when someone is trying to reach them, though there may be as much as a ~15 minute delay (minimum allowed Job Scheduler period), then there's a chance both users will foreground the app and can have a realtime conversation. I can't see a mechanism for returning messages from the GoTenna that were sent while the app wasn't running, should they just flood through on successful connection when the sdk/app starts-up?

**Comment by tcolligan-ap** [comment]
@fiskurgit The SDK should run Ok in a service I would imagine, but it isn't clear to me how that would help with stopping the app from being killed by the OS unless you used a foreground service. A job service is an interesting idea, let me know how that works out for you. We are currently exploring better ways for the SDK and our goTenna application to maintain a connection in the background, especially since Android O now has much tighter background limitations.

To answer your other question. If the goTenna has received messages while the app was not connected, upon connection it will pull all the messages one at a time, so yes, they will essentially flood through on a successful connection.

**Comment by fiskurgit** [comment]
Awesome, thanks for getting back to me. 

Yes, Android has tighter limitations now, falling more inline with how iOS operates - and that hurts the goTenna use-case more than anything else I can imagine (no luxury of push notifications obviously!). I've wrapped your public SDK in a library now that is slowly starting to come together. There's a foreground IntentService for when the user is in-app, and a background JobService which will (when I've written it) alert the user so they can start a realtime conversation. 

The wrapper api is nice; initialised in Application with `AntennaApi.init(this, GOTENNA_APP_TOKEN);` - your fragment/activity then just calls `startUISession(this, listener)` in `onResume` and `endUISession(this)` in `onPause` - this controls a foreground service but hides all the complexity. Hopefully I can find the time to carry on working on it. Will send you a message when it's developed further.

cheers.

**Comment by dferg7** [comment]
@fiskurgit if you end up getting that working please let me know. Sounds very useful for what I'm currently working on.

**Comment by fiskurgit** [comment]
It's in early messy stages at the moment: https://github.com/fiskurgit/Antenna - library is the [enkelgotenna](https://github.com/fiskurgit/Antenna/tree/master/enkelgotenna/src/main/java/fisk/enkelgotenna) module. Not remotely fit for use yet, only the foreground service is operational with only shouts/broadcasts as a proof-of-concept. The JobScheduler should be straightforward but will be a few weeks until I can spend more time on it.

**Comment by fiskurgit** [comment]
Have been exploring Services for another project, you can have a long-running Foreground Service that survives Activity death as long as it has a notification so there's nothing stopping the GoTenna solution from running all the time. Not sure if Google have relaxed things or just clarified their documentation:

> Foreground
A foreground service performs some operation that is noticeable to the user. For example, an audio app would use a foreground service to play an audio track. Foreground services must display a status bar icon. Foreground services continue running even when the user isn't interacting with the app.

 You just call `startForegroundService(intent);` then in the Service onCreate:

```
  @Override
  public void onCreate() {
    super.onCreate();

    String CHANNEL_ID = "my_channel_01";
    NotificationChannel channel = new NotificationChannel(CHANNEL_ID,
        "Some channel title",
        NotificationManager.IMPORTANCE_DEFAULT);

    ((NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE)).createNotificationChannel(channel);

    Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
        .setContentTitle("")
        .setContentText("").build();

    startForeground(1, notification);
  }
```

If I can find the time I'll start my library project again and simplify, however the official GoTenna app really needs to add this.

**Comment by tcolligan-ap** [comment]
@fiskurgit Thanks for looking into this and sharing what you found. We have essentially come to the same conclusion based on our own research as well. Other similar apps that also use a Bluetooth connection such as FitBit appear to do this also.

**Comment by benhirashima** [comment]
I use a foreground service in my unreleased goTenna app, and it works well.
My app runs for hours while regularly sending and receiving messages in the
background.

On Jan 29, 2018 7:28 AM, "tcolligan-ap" <notifications@github.com> wrote:

@fiskurgit <https://github.com/fiskurgit> Thanks for looking into this and
sharing what you found. We have essentially come to the same conclusion
based on our own research as well. Other similar apps that also use a
Bluetooth connection such as FitBit appear to do this also.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gotenna/PublicSDK/issues/27#issuecomment-361281229>,
or mute
the thread

**Comment by desrod** [comment]
I can confirm that the stock app does _not_ stay running when another app is brought to the foreground, and the goTenna hardware loses pairing (what you'd expect with a BLE device, but not a Bluetooth device). 

When the app is brought to the foreground, pairing is re-established and it takes some minutes for pending messages to be delivered and received, from other devices as well as _to_ the Android device.

It's not ideal, because you have to constantly bring the app to the foreground, wait 1-5 minutes for any potential messages to be received, and then jump back out of it again.

**Comment by tcolligan-ap** [comment]
@desrod What version of the app are you using? In the more recent versions of the Android release, there should be a foreground service that gets activated to make sure that we do not disconnect when the app goes into the background.

Also, goTenna is a BLE device (Bluetooth Low Energy) as opposed to a Bluetooth Classic device.

**Comment by dsuresh-ap** [comment]
Closing this issue as our latest Android release on the Play Store uses a Foreground Service to keep the application alive and prevent it from getting killed by the Android OS. Currently this is the best solution we have and we recommend using a Foreground Service to keep your apps alive. For better UX allow the user to toggle this feature on/off.
