### ISSUE TITLE
GT Mesh set Region

### ISSUE THREAD

**Issue by dferg7** [gotenna/PublicSDK#30]
In the read me file it says to add in this line after determining which region you are in:

GTCommandCenter.getInstance().sendSetGeoRegion(Place.NORTH_AMERICA); 

Where do we call this function? I tried to call it but it looks like its looking for response listener and error listener as well...

**Comment by tcolligan-ap** [comment]
@dferg7 You should call it first thing after the SDK says you have successfully connected to a goTenna Mesh. This function sends a command to the goTenna Mesh to let it know what Geo Region it is in so that it can change its operating frequencies to match the FCC regulations of that region.

You do not need to call this function if the app is connected to a V1 goTenna, it will just ignore the command.

**Comment by dferg7** [comment]
So could I still successfully connect with the Mesh without calling that function? 

I get all the way up to picking between which goTenna to scan for but the scan doesn't pick up the mesh, even though I ran the debugger and it returns the goTenna device type as a mesh. It just times out and says to make sure the device is on.

**Comment by tcolligan-ap** [comment]
@dferg7 Yes, you should be able to connect without calling that function. Do the connection problems occur in the provided sample application also?

**Comment by dferg7** [comment]
No, the sample is working fine, just trying to figure out why it won't pick up the connection.

**Comment by dferg7** [comment]
@tcolligan-ap calling GTConnectionManager.getInstance().clearConnectedGotennaAddress() worked. Realized my old code had it and I must've missed it when I was trying to switch over to include the mesh. Closing this issue, thank you!
