### ISSUE TITLE
Question about Text size of messages

### ISSUE THREAD

**Issue by ZeDvD** [gotenna/PublicSDK#35]
I made some tests with Mesh, and the maximum text size that can be sent is around 210 text characters. 
In the documentation, it is written " Outgoing messages are limited in size to 236 bytes"

Can you tell me what is the real text size that can be sent ? 
(May be in 236 bytes you include some headers information?)

**Comment by tcolligan-ap** [comment]
@ZeDvD How are you attempting to send the text with the SDK? Are you using one of our helper classes like `GTTextOnlyMessageData`, doing a direct serialization for text to bytes using UTF8 decoding? Or something else?

**Comment by ZeDvD** [comment]
Yes, I'm using your helper class. This is a group message. The maximum size I can send is between 200 and 210 text char (I don't have the exact number). 

On Android Studio debugger, before calling sendMessage, I see text count = 231 
On Error handler method, "Payload Limit is 235 bytes. Your message was 275 bytes."
That's why I thought that there was header information added...

Attached is copy of the debug windows.

I wanted to test with your official goTenna app but it is limited to 160 characters, so it's not possible to test with 236 characters.

![sans titre-1](https://user-images.githubusercontent.com/24782724/34680207-ac211754-f498-11e7-8fff-66d8e4afd792.jpg)

**Comment by tcolligan-ap** [comment]
Ok, yes there is some overhead that exists when using our classes.

Each piece of information we send over is surrounded by a TLV block (Type length value). So for example, if you have 32 bytes of text, that gets inflated to 34 bytes (one byte for type, indicating that it is text, one byte for length, indicating the size of the value).

We send across a couple of extra TLVs in that class for other pieces on info, so typically there should be around 9 bytes of overhead total.

It is also important to note the we convert the supplied text String into bytes using UTF8, and while that typically has a one to one ratio of characters to bytes, it does not always. Characters in UTF8 can be anywhere from 1 - 4 bytes in length depending on which ones are used.

If you want to get very lean with your data, you do not have to use our helper class. You can convert the text into data directly yourself and send it over as raw bytes. Depending on how you set this up though, it could lead to difficulties in the future with recognizing which messages contain which pieces of info at what point, which is why we provide the helper classes.
